app.py
/metrics was taking too long to load 3 days of data from graphql
=> add URL parameters for /metrics, make /metrics load faster

Dockerfile, docker-compose.yml
Makes it easy to develop locally without gitpod.io or installing python 3 locally
=> support local development via docker-compose

.gitignore, Dockerfile, data/README.md, docker-compose.yml, metrics-api.py, models/eclipses.py, models/get_stops.py, models/metrics.py, models/nextbus.py
* fetch route config from Nextbus public JSON API directly instead of restbus.info which is not currently working
* cache route config locally to reduce number of queries to Nextbus API and improve performance
* update Dockerfile to use python:3.7.2-slim-stretch as base image (can now use python instead of python3)
=> Fetch route config from Nextbus public JSON API

models/311_timetable_clean_scrape.ipynb
Added my 311 data scraper to get the timetables for a given line. I will refactor into a function later if that helps. 
**Note**: this saves the resulting csv in the '../data' folder and the notebook lives in the models folder. **Is this the right location?**
=> added 311 scraper

requirements.txt
=> Fix Jinja2 security vulnerability

frontend/src/components/ControlPanel.jsx, frontend/src/components/DropdownControl.jsx
Just some minor fixes to make the frontend look a bit nicer
=> Full Sized Buttons + Updated CP

frontend/src/reducers/routesReducer.js
Frontend was loading this error:
@jimleeisme suggested this one line change that fixes it
=> Show front page without error

.gitpod.yml
Just making it not open an extraneous blank page.
=> Small gitpod tweak

package.json
Small fix forgot to add to root package.json
=> Added exiting out when running yarn

frontend/package-lock.json
Arun's PR #73 got rid of Yarn, so I'm just going to get rid of yarn.lock and replace it with npm's package-lock.json.
=> Replace yarn.lock with package-lock.json

README.md, frontend/package-lock.json
Just added some readme text that shows you how to build the app manually (without docker)
=> Added manual build instructions

.gitignore
Just improving the gitignore to include more important lines so we don't accidentally include anything.
=> Beef up gitignore to include MacOS

constants.py, errors.py, metrics-api.py
Need an API that displays `metrics` by interval. If `start_time` and `end_time` are passed in, renders hourly metrics. Without any times attached, it shows times by the default 5 intervals that are shown on the front-end.
This code is really repetitive, still a WIP refactoring but wanted to get this API out there first.
=> Add metrics interval api

.idea/codeStyles/codeStyleConfig.xml, .idea/encodings.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/metrics-mvp.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, frontend/package-lock.json, frontend/package.json, frontend/src/components/About.jsx, frontend/src/components/Intro.jsx, frontend/src/components/Landing.jsx, frontend/src/components/NotFound.jsx
Eventually we will migrate to react hooks / functional components with everything. We are choosing to build out new components with react hooks, so switching the smallest components to react hooks is the first step in the right direction.
=> Converted small components from react components to react hooks

frontend/src/components/Home.jsx, frontend/src/components/MapStops.jsx, frontend/src/reducers/routesReducer.js
Fixes the refactoring that I didn't properly test
=> Refactoring fix

frontend/src/components/Home.jsx, frontend/src/components/MapStops.jsx, frontend/src/reducers/routesReducer.js
Rebase the reducer-fix branch onto the new master
=> Reducer fix 2

README.md
This addresses issue #136 and provides more insight into technical stack decisions, mostly around the frontend. I feel like there is room for improvement on the explanations, so feel free to make edits as you see fit.
=> Tech Stack decisions

compute_arrivals.py
For standard routes we calculate arrival times for a given day starting at 3 AM local time so midnight-3am buses are associated with previous day. For OWL routes this causes unintuitive metrics as the route is split into two days. Define OWL routes and parameterize the start time so that we get metrics that are appropriate for each route type.  This is a refactor of #144.
=> Alternative arrival calculation for OWL routes

frontend/src/components/MapSpider.jsx, frontend/src/components/MapStops.jsx
Updated base URL to https://stamen-tiles.a.ssl.fastly.net . Also, my editor automatically removed extra whitespace at the end of line.
=> use https to load map tiles to avoid mixed content warning

compute_arrivals.py
Remove the --continue-route parameter on compute_arrivals.py since it probably isn't necessary anymore.
=> Remove --continue-route parameter

frontend/src/components/Info.jsx
Not sure how it got introduced.  Fixes #191.
=> Fix typo in trip times.

frontend/src/screens/Dashboard.jsx
=> Put link to Isochrone in hamburger menu #181

frontend/src/components/MapSpider.jsx
Literally a one edit PR, this was just annoying me
=> Add a space in the Routes Near Me button

frontend/src/components/SidebarButton.jsx, frontend/src/screens/Dashboard.jsx, frontend/src/screens/RouteScreen.jsx
=> Make a reusable component for the hamburger menu

pull_request_template.md
This way we can get more consistent information from PR creators and avoid having to ask extra questions or go in and change the PR after it's made.
=> Create a pull request template

pull_request_template.md
Silly me, forgot an exclamation point so the HTML comment didn't work.
=> Quickfix: comment in pull request template

README.md
Updated the frontend section of the readme and standardized our list styles
Also linked to our onboarding documentation so if people stumble across our repo and don't know how to properly contribute, it gives them a place to start
=> README.md tweak

README.md
Fixes the issues with the readme update
=> README.md fix fix

frontend/src/components/InfoIntervalsOfDay.jsx
Simple fix, functionally was already working like a radio, now it looks like a radio box too
=> radio button fix

kubernetes/compute-new-cronjob.yaml
It normally takes about 10 minutes.
=> add cron job to automatically compute statistics once an hour

frontend/src/components/Info.jsx
Addresses #252 
coded alongside @katjone 
Still ugly, but it is more readable. More importantly, we transitioned the table from an HTML table to a material-ui-react Table component. The code is a lot easier to look at imo, and also easier to edit.
The table row text is written into an array above the return, and then mapped in. The table, and various table elements can be customized using the [material-ui Table APIs](https://material-ui.com/components/tables/#api). I would suggest a smaller font-size, which we well probably check out later, but we wanted to make sure to at least get this in today. Okay, thanks for being so welcoming last night, we both had a great time!
=> imports and implements Table component from material ui

frontend/package-lock.json, frontend/package.json
=> Package-Lock Regen

Dockerfile, backend/metrics-api.py
Adjust paths for serving static content.
=> Heroku fix for static content

frontend/package-lock.json, frontend/package.json, package.json
It appears to be unneeded in the root `package.json` file, so it was removed. Also bumped husky version in `frontend/package.json`
=> Remove Husky from Root

frontend/src/actions/index.js, frontend/src/components/Info.jsx, frontend/src/components/InfoIntervalsOfDay.jsx, frontend/src/components/MapSpider.jsx, frontend/src/components/MapStops.jsx, frontend/src/components/MareyChart.jsx, frontend/src/components/RouteSummary.jsx, frontend/src/components/TravelTimeChart.jsx, frontend/src/screens/Dashboard.jsx, frontend/src/screens/Isochrone.jsx, frontend/src/screens/RouteScreen.jsx
- Removed unused vars
- Resolved shadowing
- Fixed used before define
- Changed nested tertiary navs
- Undid merge conflict improperly resolved (unused vars)
=> Beautify Round #6

kubernetes/save-routes-cronjob.yaml
Add --s3 argument to save routes cronjob so output is saved to s3.
=> Add --s3 argument to save routes cronjob so output is saved to s3.

frontend/src/components/MareyChart.jsx, frontend/src/components/RouteSummary.jsx, frontend/src/components/RouteTable.jsx, frontend/src/screens/Dashboard.jsx, frontend/src/screens/DataDiagnostic.jsx, frontend/src/screens/RouteScreen.jsx
- MareyChart: Fix a 404 error (in the console only) trying to fetch data before routeId is set
- useEffect usage:  as suggested by the error, destructure props and include each part of props as a dependency.
n/a
n/a
=> Fix a 404 error in the MareyChart and fix useEffect lint warnings

frontend/public/index.html
Fixes #331.
Add Google Analytics code to top level index.html.  Use javascript to run this code only for opentransit.city URLs as suggested here: https://stackoverflow.com/questions/1251922/is-there-a-way-to-stop-google-analytics-counting-development-work-as-hits
n/a
n/a
=> Add Google Analytics code (for production site only)

docs/README.md
I mistakenly deleted our readme in #352, lol. Please approve this to roll back that mistake.
=> put back readme documentation

frontend/src/components/SidebarButton.jsx
Add a link to our homepage in the sidebar.
https://open-transit-about.herokuapp.com/
Any comments are welcome.
=> add about link

frontend/src/screens/Isochrone.css, frontend/src/screens/Isochrone.jsx
=> Added Clear button and converted the toolbar to Material per #342

backend/models/schema.py, docs/metrics_api.md
Implements the graphql schema specified by @youngj in
trynmaps/metrics-mvp#301 and changes byDay to use an arbitrary array
of dates.
```
type TripMetrics {
byDay(
dateStrs: [String]
startTime: String
endTime: String
): [BasicIntervalMetrics]
}
type BasicIntervalMetrics {
startDate: String
endDate: String
startTime: String
endTime: String
waitTimes: BasicWaitTimeStats
tripTimes: BasicTripTimeStats
}
type BasicWaitTimeStats {
median: Float
percentile(percentile: Int!): Float
probabilityLessThan(minutes: Int!): Float
}
type BasicTripTimeStats {
median: Float
percentile(percentile: Int!): Float
}
```
...
...
...
=> Implement date ranges on the Backend

backend/models/schema.py
Fix inadvertent removal of config import from schema.py that was breaking graphQL queries.
Looks like there was a force push in https://github.com/trynmaps/metrics-mvp/pull/372/files that resulted in the conflict on line 1 of schema.py being ignored.
```
metrics-flask-dev | NameError: name 'config' is not defined
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File …
```
=> Production: stop to stop stats not working.  Fix for graphQL query error.

backend/models/schema.py
Fixes #455
https://metrics-mvp-brians-fork.herokuapp.com/
This is my first pull request. I am not certain I fixed the issue #455 as it is not trivial for me to generate and observe the issue behavior. However, I think it might fix it, and I don't think it should hurt.
=> added exception for wait_time_median.get_value() returning None

frontend/src/components/SidebarButton.jsx
Fixes warnings about use of == instead of === in SidebarButton.
n/a
n/a
=> Fix warnings.

frontend/src/screens/RouteScreen.jsx
Taking @youngj changes and adding UI  portion (breadcrumbs)
Fixes #160
...
=> Adding Breadcrumbs UI

frontend/package-lock.json, frontend/src/components/MapSpider.jsx
Adds a conditional to check for existing color in startMarker.routeInfo and sets color to corresponding color.  If null, uses color generated by index.  
...
=> Max colors

frontend/src/actions/index.js, frontend/src/components/Info.jsx, frontend/src/screens/DataDiagnostic.jsx
Quick feedback items from #461.
- index.js: Add documentation about Redux thunks.
- Info.jsx: Add documentation about why there currently is no "by day" data for date range comparisons.
- DataDiagnostic.jsx: Fix typo that broke page and remove unneeded text.
n/a
n/a
=> Feedback on #461

README.md
I have some tweaks/refinements to the README here, I am proposing:  They are from myself having followed the existing README at last week's PDX meeting (my first) to setup my local environment.
I look forward to more PR's and working with everyone!
=> Refine readme `Building the app` instructions.

backend/models/metrics.py
Fixes #547.
Avoid returning concatenated empty arrays by changing the conditional for three return statements from straight ELSE clauses to ELIF len(array) != 0
Ultimately  this avoids an ugly error message for the user, returning nothing when no results exist.
e.g.
elif len(completed_trips_arr) != 0:
....return np.concatenate(completed_trips_arr)
Ultimately, I think a bigger issue is the front-end, which allows a user to select zero effective days by filtering the date range to only weekends (for example)
...
...
...
=> fixes #547 again-

backend/models/trynapi.py
#618 stopped caching empty state files for routes with no data, which meant that trynapi.get_state would need to request the entire day's worth of data for those routes if it was called again. This PR creates empty CSV files for routes with no data, so that it's faster to re-run compute_arrivals.py once the state is already cached.
=> create empty cache files so that get_state doesn't need to request routes with no data again

frontend/src/components/DateRangeControl.jsx
…times each
Fixes #633 
Also, addresses the code style issues that should have been done in PR #628 
...
=> fixes #633 and code style improvements

frontend/src/screens/Home.jsx
Just updates the text on the home screen to give more context about the project. We can add more sophisticated stuff and an onboarding flow later, I just want to make sure we get a small update out.
=> Refresh home screen

.github/workflows/deploy.yml
Change the working directory to frontend to fix build and deploy errors
=> Deploy workflow fix

.github/workflows/deploy.yml
=> Revert deploy script

backend/models/timetables.py
Resolves https://github.com/trynmaps/metrics-mvp/issues/647
As to identify the GTFS date corresponding to a given
date (ie. the GTFS date containing the scheduled trips
for that date) a date_keys lookup is done.
The lookup is done on the date_keys file, which persists
the GTFS date for each date that was processed, as to allow
for re-running pre-computation on older GTFS's.
Since the recentmost GTFS file Muni put out expired on 2020-05-29,
the pre-computation as well as the API failed due to the date key
lookup failing.
This PR modifies the get_date_key function as to return the
recentmost date key corresponding to the same day of the week.
Note that it does not take holidays into account. It raises
an exception if it cannot find a suitable date_key to use.
It prints a warning if it …
=> Use recentmost date key if date is not active in GTFS
