- frontend/package-lock.json
- models/eclipses.py
- models/get_stops.py
- models/metrics.py
- models/wait_times.py
`get_stops` can now either query graphql (with the same parameters as before) or can take raw json data from a previous query. Moved functions for computing the wait times to another file.
> Refactored backend functions for getting stops and wait times

- compute_arrivals.py
- get_state.py
- headways.py
- metrics-api.py
- models/arrival_history.py
- models/eclipses.py
- models/nextbus.py
- models/trynapi.py
- trips.py
- vehicle.py
This PR contains several changes related to computing and using arrival history:
Previously, compute_arrivals.py previously worked for one route at a time, but it is probably faster to compute arrivals for multiple routes at once (since tryn-api reads the state data from S3 containing all routes, before dropping the data from any routes that were not requested)
To compute arrivals for all routes, omit the `--route` argument:
```python compute_arrivals.py --date=2019-03-01```
To compute arrivals for multiple named routes, separate the routes by spaces after the `--route` argument:
```python compute_arrivals.py --date=2019-03-01 --route 38 38R 38AX 38BX```
Sometimes tryn-api runs out of memory when fetching 24 hours of data at once. compute_arrivals.py now splits requests into smaller …
> Improve arrival history

- README.md
Clearing this task:
https://trello.com/c/vpEJ46hF/130-update-documentation-to-tell-people-to-use-npm-run-build-to-make-a-prod-build
> Updated documentation to regenerate production

- frontend/src/components/Info.jsx
- metrics-api.py
- models/wait_times.py
Using the timetable data for first/last bus times was causing the maximum wait time for most routes to be very large, which threw off the statistics, so I just changed it to use the first/last actual arrival for now.
> only show wait times between first and last actual arrival

- frontend/src/components/ControlPanel.jsx
- models/arrival_history.py
- models/util.py
- models/wait_times.py
In order to support filtering by times after midnight, this introduces the convention of adding "+1" at the end of the time string, like "03:00+1". Instead of using an alphabetic comparison of the time string, we can call util.get_localized_datetime to get a datetime for the time string, and then compare datetimes.
> allow filtering by time range

- .gitpod.yml
Currently it's impossible to run the app in Gitpod because Gitpod defaults to using Python2 but our app uses Python3, leading to syntax errors. Ideally I would make Gitpod use our Docker image but I can't find a way to install Docker on Gitpod so we can do `docker compose up`. So for now we'll just re-run all the stuff contained in the dockerfile manually.
Thus, for now, we'll just force Gitpod to use Python3. Small patch, but it'll work for now. Again, ideally we would get Gitpod to read from the dockerfile but that's not possible right now.
Fixes #62.
> Make Gitpod use Python3

- frontend/public/index.html
Minor change to just change the landing page's title
> Make app say "OpenTransit" instead of "React App"

- .gitignore
- Dockerfile
- docker-compose.yml
- frontend/package.json
After switching from yarn to npm, `docker-compose up` has been taking a very long time to start the react container, due to the call to `npm install`, which sometimes seems to hang forever. (Also tried `npm ci` but it didn't seem to help.)
With this change, the react docker container uses the package.json, package.lock, and node_modules from when the docker image was originally built (which happens the first time you run `docker-compose up`), and only the `/frontend/{build,public,src}` subdirectories are shared between the host and the container. This makes it no longer necessary to run `npm install` during `docker-compose up`, so now the react container starts quickly (~5 seconds).
The downside is that any time node dependencies are changed in package.json, the docker container must be …
> update docker-compose to use node_modules folder created when docker container originally built

- .gitignore
- compute_arrivals.py
- frontend/src/components/ControlPanel.jsx
- get_state.py
- models/arrival_history.py
- models/eclipses.py
- models/nextbus.py
- models/trip_times.py
- models/trynapi.py
- models/util.py
- requirements.txt
- route.py
- vehicle.py
This PR implements several changes to the algorithm for computing arrival times from GPS observations to improve correctness and performance.
**Variable eclipse distance**
Instead of using a fixed 200m radius to determine when a bus reaches a stop, it now uses the smaller of 200m or the distance to the nearest adjacent stop along the route. It also requires the bus to be closer to that stop than the previous or next stop. This fixes most weird issues near the end of certain routes where the bus never leaves a 200m radius of the second-to-last (or third-to-last) stop.
There are still some unfixed edge cases like the 30 to Jefferson Loop which reaches the corner of Chestnut and Divisadero twice while going in the same "direction".
**Second pass to add missing stops**
Sometimes the first …
> Optimize arrival time calculations

- frontend/package.json
- frontend/src/UIConstants.js
- frontend/src/components/Info.jsx
- frontend/src/components/InfoIntervalsOfDay.jsx
- frontend/src/helpers/graphData.js
As mentioned in https://github.com/trynmaps/metrics-mvp/issues/90 , we wanted to replace the react-d3-components charts with react-vis charts.  These new charts are more customizable, allow hover tooltips, and for now, have a fixed width so that the page doesn't get super wide for unusual histograms.  If needed, later we can make these flexible width.
Normal histograms:
Unusual histograms:
> Replacing react-d3-components charts with react-vis

- models/trynapi.py
Since tryn-api has been updated to the secsSinceReport field, we can now request secsSinceReport in order to correctly resample GPS observations by adjusting for how old the GPS observation was when orion retrieved it from the Nextbus API.
> always request secsSinceReport field from tryn-api

- frontend/src/components/ControlPanel.jsx
- metrics-api.py
- models/nextbus.py
The UI design in our roadmap works best with full route configs loaded up front.  This is so that the "spider" map can show all routes that stop near a point, and so that the "home" screen can list all routes and directions (directions are not part of the current route list).  The route configs will be used together with the precomputed trip/wait isochrone data to show grades and rankings for all routes.  Instead of a `/routes` and `/routeConfig` endpoints, there is just a single `\routes` endpoint that returns all route configs.
The volume of data fetched from Nextbus is about 780kb, and with added whitespace becomes 900kb sent from the back end to the front end.
This change is meant to be easily reversible in case issues are discovered with it.  There are other ways for the front end to …
> Roadmap UI: Allow the UI to load all route configs up front instead of one at a time on demand.

- frontend/public/index.html
There was a HTTP 307 redirect each time the app is loaded from a http URL, slowing down the page load slightly.
> always load leaflet.css with https:// URL since http URL redirects to https anyway

- compute_trip_times.py
- compute_wait_times.py
Added --start-date and --end-date arguments to compute_wait_times.py and compute_trip_times.py to make it easier to compute historical statistics
> allow computing trip time and wait time stats over a date range

- frontend/src/actions/index.js
- frontend/src/components/MapStops.jsx
- frontend/src/components/RouteTable.jsx
- frontend/src/helpers/precomputed.js
- frontend/src/reducers/fetchGraphReducer.js
- frontend/src/reducers/routesReducer.js
Porting over some more stuff from my experimental branch.  To show speeds along a route, we need to fetch the precomputed trip times from S3.  I used Jesse's isochrone branch as a guide for implementing storage of the trip times and wait times in Redux.  helpers/precomputed.js has some of the same utility methods.
Currently, I'm using the `handleGraphParams` action creator as the trigger for loading the cache, so that when a route is chosen, we make sure the cache is loaded.  Loading the Dashboard screen will probably also have to trigger loading since the RouteTable will use the cache also.
Plotting speeds will probably need some refinement.  Speeds are plotted whether just one or all directions are shown.  If multiple directions are visible, then you can't see all the speeds.
Should be …
> Show speed along route

- kubernetes/managed-certificate.yaml
- kubernetes/web-ingress.yaml
- kubernetes/web-service.yaml
I already applied these YAML files were applied to the GKE cluster to create a Google-managed certificate for muni.opentransit.city and an HTTPS load balancer that routes https://muni.opentransit.city/ and http://muni.opentransit.city/ to the web service. The web service is now exposed on port 80 on each host in the cluster instead of using a TCP load balancer like before (which didn't support SSL termination). 
With this configuration Google will automatically renew the SSL certificate as long as muni.opentransit.city points to the load balancer.
I generally followed the instructions at https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs but without creating a reserved IP address (not sure if this means that GKE will automatically delete the IP address if the Ingress is …
> use Google managed SSL certificate in GKE

- frontend/src/components/MapStops.jsx
- frontend/src/components/RouteTable.jsx
- frontend/src/helpers/precomputed.js
I moved the speed calculation code that deals with the trip times cache back into `precomputed.js` so that it can be reused.  The diff is hard to read, but basically `precomputed.js` is back to being like Jesse's isochrone functions.  I put in some JSDocs for each function.  The differences are that fetching of the s3 files is done elsewhere, and date and time are passed in using graphParams.
The routes table on the Dashboard screen is now using the wait times cache, to show the median wait for each route.  Actually, it's average of the median wait in each direction.
> Refactoring speed computation and using actual median waits in RouteTable

- kubernetes/flask-deployment.yaml
- kubernetes/web-deployment.yaml
Currently our Kubernetes cluster has one n1-standard-1 instance which has 0.94 allocatable "CPU units". Kubernetes built-in services automatically request about 0.60 CPU units, leaving only 0.34 CPU units for requests from our app. By default, each container requests 0.1 CPU units, so it is only possible to run 3 containers in the cluster before Kubernetes is unable to schedule new pods because of insufficient CPU. Currently the instance shows about 10% CPU utilization on average, so the containers are not actually using all the CPU units that are allocated to them. 
By only requesting 0.03 CPU units per container, we can run 10 containers on our current instance before getting an error from Kubernetes about insufficient CPU. It is possible for the containers to use more CPU than they …
> change flask/web deployments to request 0.03 cpu instead of 0.1 cpu 

- models/errors.py
- models/gtfs.py
- models/timetable.py
Previously, the GTFS scraper wouldn't update the list of possible date ranges for timetables when adding additional timetables, which would cause errors when fetching timetables for certain dates. Now the scraper will append additional date ranges to `date_ranges.csv` when it runs.
> Update gtfs scraper to update date_ranges.csv

- README.md
- frontend/public/isochrone-worker.js
- frontend/src/actions/index.js
- frontend/src/components/MapSpider.jsx
- frontend/src/screens/Isochrone.jsx
- metrics-api.py
- save_routes.py
This PR makes it possible for the frontend to draw the actual route traveled between two stops (instead of drawing straight lines between each stop), and to get the distance along a route between two stops, which can be used to for more accurate speed calculations.
The command line script save_routes.py downloads and parses the GTFS specification (hardcoded for Muni for now), matches up GTFS shapes with Nextbus directions and stops, and saves the configuration for all routes to S3 (https://opentransit-precomputed-stats.s3.amazonaws.com/routes_v1_sf-muni.json.gz). The S3 object contains data merged from Nextbus and GTFS, extending the JSON data structure previously returned by /api/routes. The frontend can then request this S3 URL instead of /api/routes .
For each direction, the JSON …
> Extract route geometry from GTFS files

- frontend/public/index.html
Currently URLs like http://muni.opentransit.city/route/10 with a slash in the path are broken because create-react-app replaces %PUBLIC_URL% with `frontend/build`, not `/frontend/build` . This PR adds a `base` tag to the HTML so that all relative URLs are loaded relative to the domain root instead of the current "directory" of the URL path.
> fix loading URLs with slashes in production environment

- frontend/public/isochrone-worker.js
- frontend/src/App.css
- frontend/src/screens/Dashboard.jsx
- frontend/src/screens/Isochrone.css
- frontend/src/screens/Isochrone.jsx
- frontend/src/screens/RouteScreen.jsx
Instructions for the isochrone map are shown in the top right when not showing trip information.
> add the app bar to the isochrone map and use its date/time selector; add instructions to isochrone map

- frontend/src/components/TravelTimeChart.jsx
- frontend/src/helpers/routeCalculations.js
Shown is the 8AX inbound.  Stop number is now part of the `Crosshair` tooltip and total number of stops is shown with full route length.
The stop index business has always been a little funny since stop index 0 is the "first stop" after we slice off the starting terminal, which always has zero travel time.  Not sure if we should just plot times starting from the terminal, was copying nycbusstats by doing the slice.
Deployed to http://ot-terence.herokuapp.com
> Travel time chart x-axis is now distance instead of stop number

- frontend/src/screens/Dashboard.jsx
- frontend/src/screens/Isochrone.css
- frontend/src/screens/Isochrone.jsx
- frontend/src/screens/RouteScreen.jsx
(Note: when there are too many files with warnings, React stops logging additional warnings to console.  This makes it harder to catch additional issues.)
- Fix warnings around unused imports and constant 
- Fix warnings around use of != and ==.
- Change \<a href="javascript:void(0)"> to \<span> per accessibility warning advice at https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md, update css to make span resemble link.  In the future, we could use Material UI components, such as small buttons, although they won't be as compact as the text link.
> Fix some React console warnings (no visible changes).

- frontend/src/components/MapSpider.jsx
There were click handlers in `MapSpider` that were calling handleGraphParams followed by push('/route').  After Chris' merge, these were returning a 404 page.  Looks like the quickest fix for now is to push a fully parameterized URI.  There may be a better way (like getting the redux state change and the routing change done just by dispatching an action), but this works for now.
> Fix links in the spider map by using routing.

- compute_arrivals.py
- compute_new.py
- compute_trip_times.py
- compute_wait_times.py
compute_new.py checks S3 to see the last date that has been fully computed, and starts computing arrival times, wait time stats, and trip time stats on the next day and advances until it reaches the current day. It could be run in Kubernetes as a cron job (not in this PR) to automatically compute the necessary stats. It could also be run more than once a day in order to provide near-real-time stats for the current day.
> script to compute new arrival times, wait time stats, and trip time stats

- models/eclipses.py
The print statement raised an error because num_trips was undefined when there were no possible arrivals.
> fix bug when a route has 0 arrivals

- frontend/src/App.css
- frontend/src/components/ControlPanel.jsx
- frontend/src/components/MapSpider.jsx
- frontend/src/components/MapStops.jsx
- frontend/src/components/RouteSummary.jsx
Initially it shows the message "Click anywhere in the city to see the routes near that point."
When routes are displayed, it shows the message "Click anywhere along a route to see statistics for trips between the two stops."
Also works around a bug that I didn't fully understand where "grades" object could be null on the route screen after clicking the spider map.
> add instructions for spider map and route map

- frontend/src/components/MapSpider.jsx
- frontend/src/components/QuadrantChart.jsx
- frontend/src/components/RouteSummary.jsx
- frontend/src/components/RouteTable.jsx
- frontend/src/components/TravelTimeChart.jsx
- frontend/src/helpers/precomputed.js
- frontend/src/helpers/routeCalculations.js
- frontend/src/screens/Dashboard.jsx
- MapSpider: use precomputed wait values to choose thick/med/thin lines based on frequency instead of hardcoded wait values.
- routeCalcuations.getSpeedForRoute: Remove getAllDistances in favor of using the GTFS-based distance per direction
- Refactor code to pass direct objects to getAllSpeeds, getAllWaits, and getAllScores, instead of just props.
Fixes #235.
No real visible changes, except that the spider map lines all become thin while loading new precomputed wait times.
Demo at https://ot-terence.herokuapp.com/
> Fixes #235: better speed calculation, also refactor parameters passed to getAllSpeeds, getAllWaits, getAllScores

- CODEOWNERS
This will help with auto suggesting reviewers
It'd be better if we moved the python stuff into a `/backend/` folder so we can maintain this cleaner as a mono repo and make the file structure of this repo suggest code owners properly. Ideally better than maintaining a document that suggests code owners to tag
> Codeowners to auto suggest reviewers

- frontend/.eslintrc.json
I'm going to break up the clean up / beautification of the codebase into smaller parts since the codebase changes so match it's basically asking for conflicts
- Makes going over the max length a warning instead of an _error_
- destructuring isn't mandatory
- makes using `_foo` or `foo_` or any dangling underscore a warning
- makes props a warning
> Updated Prettier Rules

- frontend/src/components/MapSpider.jsx
- frontend/src/screens/Dashboard.jsx
- frontend/src/screens/RouteScreen.jsx
Fixes #268.
- Use the "sm" breakpoint (640px window width) to be breakpoint where map becomes half of the screen width (`MapSpider` and `MapStops`), and full width below that.
- `MapSpider` was always full height but now is half height if window width is less than 640px.
Note: `MapStops` is currently fixed height, 500px.  We could make it more like MapSpider if we wanted.
Note:  The Material UI `Table`s don't do well in narrow windows.  They have a lot of padding in the columns.  Need to address this is another issue/PR.
Not available.  No visible changes for larger screens.
> For small windows (640px), make dashboard map and route screen map full width

- frontend/src/components/RouteTable.jsx
Fixes #231.
The route data contains `NaN`s which require special case handling for sorting.  This is because NaN < 3 evaluates to false, as does NaN > 3, which breaks sorting.
> Fix sorting of "--" (Nan) values in RouteTable

- backend/metrics-api.py
Running `docker-compose up` tells the user to visit port 5000, but that just gives them the "this is the api server" message, with no direction to the app. This has confused many new OpenTransit'ers.
This commit adds a note that the user should visit port 3000 to see the real app.
> Improve documentation on port 5000

- kubernetes/save-routes-cronjob.yaml
Currently it just overwrites https://opentransit-precomputed-stats.s3.amazonaws.com/routes_v2_sf-muni.json.gz (not storing historical data yet). 
The GTFS feed at http://gtfs.sfmta.com/transitdata/google_transit.zip doesn't include 78X or 79X yet.
> add cron job to update routes JSON once a day

- kubernetes/compute-new-cronjob.yaml
The cron job to compute new arrivals and stats previously hung in the middle of a run (not sure why). Limiting the run time of a cron job should hopefully work around this.
> add 10000 second time limit to cron job so it doesn't get stuck

- backend/models/arrival_history.py
- backend/models/eclipses.py
- backend/models/trip_times.py
- backend/models/wait_times.py
- frontend/public/isochrone-worker.js
- frontend/src/actions/index.js
- frontend/src/locationConstants.js
The Marey chart highlighted some issues with the arrival time calculation, especially on Muni Metro routes, where there were many long gaps in arrival times for one vehicle that were being counted as part of a single trip (when most likely that vehicle was out of service during the gap):
Example (KT on 9/27):
To fix this issue, the arrival time algorithm now counts arrivals as belonging to separate trips if there is a gap of 3 or more stops, or if there is a gap of 30 or more minutes without any GPS observations from that vehicle (indicating that the vehicle was likely not in continuous service during that time).
The algorithm does not have any limit on the travel time between stops (e.g. 1 hour). It is possible that a bus may actually be in service between those two stops but waiting a …
> count arrivals as belonging to separate trips if there is a gap of 3+ stops, or 30+ minutes of missing GPS observations

- frontend/src/components/RouteTable.jsx
Fixes #164.
When sorting by route name (internally `title`), use the natural order of the routes array, which comes from Nextbus. It is the simplest way to get a "good" ordering for the routes without having to implement a hybrid numeric/lexical sort.
n/a
> Dashboard: Fix sorting of routes by name (title).

- frontend/src/UIConstants.js
- frontend/src/components/ControlPanel.jsx
- frontend/src/components/MapStops.jsx
Changes the map of stops so that a larger map legend isn't needed:
- Make all stops the same indigo color
- Add "from stop" and "to stop" icons in black.  The model for this is the Google Maps UI, where these icons appear next to the corresponding form inputs as well on the map.
File level changes:
- `ControlPanel`: add "from stop" and "to stop" icons next to the pulldown menus
- `MapStops`:
- add "to stop" and "from stop" icons to the map
- make all other stops the same color (indigo)
- rename `populateRouteDirection` to `populateStops`
- move the call to `populateSpeed` out of `populateStops` so that the speed lines stay under all the stop markers of all directions
- `UIConstants`: new indigo color from the Material UI palette for stop markers.
https://ot-terence.herokuapp.com
> MapStops improvements

- frontend/src/components/RouteTable.jsx
Fixes #339.
Remove `Paper` around route table, as this creates unnecessary borders and shadows around the table.  Style the route links using the theme's primary dark color and no underline.
n/a
> Remove Paper around route table and style links.

- frontend/src/components/InfoTripSummary.jsx
- frontend/src/components/RouteSummary.jsx
Fixes #343.
Adjust "Wait" in the tooltip to "Median Wait". Making it consistent with the "Median Wait" on the card. This change applied to two places. See screenshots below for reference.
...
...
...
> wenyu's good first issue

- nginx/conf.d/web.conf
Fixes #162 
Adds a rule to nginx config to to redirect to HTTPS if the "X-Forwarded-Proto" header is "http"
Unfortunately, the heroku deployment does not use nginx. However, you can verify this locally.
First, start the application using the prod configuration:
```
docker-compose -f docker-compose.prod.yml
```
In a separate terminal, run:
```
curl -v -H 'x-forwarded-proto: https' http://localhost:8080
```
Expected output:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> x-forwarded-proto: http
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.16.0
< Date: Thu, 24 Oct 2019 03:22:47 GMT
< Content-Type: text/html
< Content-Length: 169
< Connection: keep-alive
< Location: …
```
> Redirect HTTP to HTTPS 

- frontend/src/components/MapStops.jsx
- frontend/src/components/RouteTable.jsx
- MapStops:  implement svg rotation using \<g> for compatibility with macOS/iOS Safari  (Chrome and Firefox implement `transform` for the `svg` tag, which is an SVG 2 feature.  https://stackoverflow.com/questions/48248512/svg-transform-rotate180-does-not-work-in-safari-11
- RouteTable:  remove unused import
n/a
n/a
> Minor bug fix for MapStops on Safari

- backend/models/eclipses.py
- backend/models/trynapi.py
- docker-compose.yml
Updates metrics-mvp to support tryn-api changes in https://github.com/trynmaps/tryn-api/pull/46 with timestamps in seconds, exclusive endTime parameter, and some different field names. Will need to also update the default tryn-api URL before merging.
> update backend to use new tryn-api

- frontend/src/App.css
- frontend/src/components/ControlPanel.jsx
- frontend/src/components/MapStops.jsx
Fixes #272. Improves PR #362.
Use a different approach to create "hover over stops" effect.  Instead of letting React rerender the whole routes (see PR #362 for detailed performance issue), it adds an "on-hover" className to the stop that being hovered. The "on-hover" class uses a pseudo class **.on-hover::before** to add stop title.
Proposed changes
When you hover over entries in the To & From Dropdowns, the stop/route on the map will update correspondingly. So you know exactly where the stop you're hovering is on the map.
Link to demo, if any
https://open-transit.herokuapp.com/route/M/direction/M____O_D00/fromStop/6996/toStop/7125
> Hover over stops - faster

- .dockerignore
- Dockerfile
Apparently %REACT_APP_METRICS_BASE_URL% is replaced in index.html when running the development server, but is not replaced when running `npm run build`. This caused https://muni.opentransit.city/ to stop working. To fix this, replace %REACT_APP_METRICS_BASE_URL% when building production assets in the Dockerfile.
> replace %REACT_APP_METRICS_BASE_URL% with empty string in production index.html file

- Dockerfile
A less hacky way to do https://github.com/trynmaps/metrics-mvp/pull/418
> set REACT_APP_METRICS_BASE_URL to empty string in Dockerfile so that %REACT_APP_METRICS_BASE_URL% is replaced in index.html

- frontend/src/UIConstants.js
- frontend/src/components/InfoScoreCard.jsx
- frontend/src/components/InfoScoreLegend.jsx
- frontend/src/components/InfoTripSummary.jsx
- frontend/src/components/RouteSummary.jsx
- frontend/src/components/RouteTable.jsx
- frontend/src/helpers/routeCalculations.js
On the stop to stop page:
- Rename "90% of trips" to "most trips (less than)"
- Add an info icon for "most trips" to explain that "most" is 90% of trips.
- Add an expanded definition of travel variance to the popover.
On the route summary:
- Add an expanded definition of travel variance to the popover.
On the route table:
- add a popover explaining the column titles.
Also on these three pages:
- Rename "extra travel" to "travel variance"
- Limit popover widths to 500px max.
Stop to stop with "most trips (less than)" and "travel variance":
Stop to stop with travel variance popover:
Route summary with travel variance popover:
Route table, new column headings and info icon:
Route table with popover:
n/a
> Wording fixes.

- .github/labeler.yml
- .github/workflows/label.yml
This creates a GitHub action that auto-labels PRs based on the files they change. If you touch the backend directory, for instance, your PR will get a Backend label. This should help us sort through the ever-increasing number of PRs more efficiently.
> Auto-label PRs

- docs/deployment.md
- kubernetes/compute-new-cronjob.yaml
- kubernetes/save-routes-cronjob.yaml
This allows computing arrivals for other agencies besides `muni` (although the web app still only shows `muni`). 
The actual ConfigMap isn't checked into the repo since different deployments could have different configs. 
To deploy the web UI for other agencies, it would probably be easiest to use Kubernetes namespaces (or a separate Kubernetes cluster).
> configure agency IDs for kubernetes cron jobs via ConfigMap

- docs/metrics_api.md
Fixes #453, which references that #372 accidentally (we think?) removed a section from the documentation.
> fix missing documentation

- frontend/src/components/ControlPanel.jsx
Fixes #426 
* Please provide any feedback as this is my first pull request on an open source project.
> handle loops correctly when displaying list of stops in the UI issue 426

- backend/agencies/muni.yaml
- frontend/src/components/MapStops.jsx
- frontend/src/components/TravelTimeChart.jsx
- frontend/src/helpers/routeCalculations.js
Fixes #439 and supersonic 29-Sunset.  Fixes #407.  
- muni.yaml: Updated muni.yaml for GTFS stop ids and E/F temporary turnaround at pier 39.  Fix for supersonic 29 sunset speed by ignoring starting inbound stops that are too close (tight "U"). (#439)
- MapStops: Minor layout fix for map height to compensate for new breadcrumb area (from #415)
- TravelTimeChart and routeCalculations:  compute route speed with more accurate distance based on starting and ending stops as outlined in #407.
Improved speed for E and F on the left:
Improved speed for 29 and also routes that double back, like 36 and 39, on the left:
Route summary layout fix on left, map not cut off vs cut off map and scroll on right:
https://ot-terence.herokuapp.com/
> Speed calculation fixes

- frontend/src/components/SidebarButton.jsx
- frontend/src/reducers/page.js
Fixes #402. 
Menu now disappears when clicking anywhere else on the page.
Fixes #390.
Dot is replaced with a meaningful label. Added icons.
Fixes #381.
Brings the rest of the menu in line with the Material-UI of the 'About' link.
Fixes #472.
Hover and active page works now.
> Beautified the Sidebar with Material-UI

- frontend/src/components/RouteTable.jsx
- frontend/src/helpers/routeCalculations.js
Related to #429.
Color table cells with metric values (wait, speed, etc.) by quartile.  Add units (min, mph) to each cell's value.
http://wpg-opentransit.herokuapp.com
> RouteTable:  use filled Chips with light background colors and add units

- backend/agencies/muni.yaml
- backend/models/gtfs.py
save_routes.py was raising an exception because the custom directions for Muni 47 and 83X changed and the custom direction stop filters no longer matched any shapes in the new GTFS feed. Since Muni 47 and 83X only have 1 shape per direction in the new GTFS feed, the custom direction configuration can be removed now (note that storing old route configuration has not yet been implemented).
Also, fixes a bug where save_routes.py raised another exception while trying to raise the first exception because `route_id` was not defined in `get_custom_direction_data`.
> Fix save_routes failing because muni routes changed

- backend/models/metrics.py
- backend/models/schema.py
- backend/models/wait_times.py
- backend/waits.py
- docs/metrics_api.md
Fixes #488.
The GraphQL API allows returning wait time statistics over multiple days, but previously the returned statistics were only actually from the first day.
This PR implements a MultiIntervalWaitTimeStats class that returns statistics over multiple intervals, assuming each interval is weighted equally (not weighted by their length).
Most wait time statistics (other than the average) are computed from the cumulative distribution function (CDF), which gives the probability of having a wait time less than a given number of minutes if someone arrives at a stop at a random time between the first and last departure time of the day. 
With each interval weighted equally, the probability of a wait time less than a given number of minutes (CDF value) is the average of the values of the CDFs …
> Compute wait time statistics over multiple days

- backend/compare_versions.py
- backend/compute_trip_times.py
- backend/models/arrival_history.py
- backend/models/eclipses.py
- backend/models/gtfs.py
- backend/models/metrics.py
- backend/models/routeconfig.py
- backend/models/trip_times.py
- backend/models/wait_times.py
- backend/route.py
- backend/trips.py
- backend/vehicle.py
- backend/waits.py
- frontend/public/isochrone-worker.js
- frontend/src/actions/index.js
- frontend/src/components/ControlPanel.jsx
- frontend/src/components/InfoTripSummary.jsx
- frontend/src/components/MapSpider.jsx
- frontend/src/components/MapStops.jsx
- frontend/src/components/MareyChart.jsx
- frontend/src/helpers/mapGeometry.js
- frontend/src/helpers/routeCalculations.js
Fixes #312.
Fixes #425.
Fixes #465.
Previously, eclipses.py did not do a good job at grouping arrivals into trips for certain routes. The previous algorithm simply looked for 3 adjacent possible arrivals with ascending stop indexes. However, for routes that doubled back on themselves (or nearly so) there would be out-of-order possible arrivals between the actual arrivals.
For twisty routes where a single direction doubles back on itself (or nearly so), such as SF Muni's 39-Coit, 36-Teresita, 30-Stockton, 9-San Bruno, etc., it is possible that there may be out-of-order stop indexes in the "possible" arrivals.
As an example, suppose consecutive stop indexes of possible arrivals for some route is 1,2,6,3,7,4,5,6,3,4,7,8,9. In this case, the "best" trip has the stop indexes 1,2,3,4,5,6,7,8,9. …
> Improve algorithm for generating trips from possible arrivals; handle loops, figure-eights, routes that double back

- backend/models/gtfs.py
- backend/models/routeconfig.py
- backend/models/trip_times.py
- backend/tests/test_schema.py
- backend/tests/test_trip_times.py
- backend/tests/test_wait_times.py
This repo now has a testing framework for backend Python code, but there is a lot of existing code that doesn't have any tests yet.
I added some tests for computing trip times (including loop routes) and wait times (including combining statistics for multiple intervals). 
Also, refactored the code for saving route configuration so that tests can save route configuration more easily.
There are several modules that still need tests, including eclipses, gtfs, routeconfig, timetables, and trynapi.
> Add unit tests for computing wait times and trip times

- backend/models/gtfs.py
- frontend/src/actions/index.js
One of the routes in Trimet's current GTFS feed has no "short name" or "long name", which caused save_routes.py to save the route title as NaN in the JSON file, which caused an error when the frontend tried to parse the JSON file. This PR fixes this issue by using the GTFS route ID as the title if the route has no short name or long name in the GTFS feed.
> fix bug with invalid routes JSON if route does not have short name or long name in GTFS feed

- frontend/src/actions/index.js
- frontend/src/components/InfoScoreCard.jsx
- frontend/src/components/InfoScoreLegend.jsx
- frontend/src/components/InfoTripSummary.jsx
- frontend/src/components/MapSpider.jsx
- frontend/src/components/RouteSummary.jsx
- frontend/src/components/RouteTable.jsx
- frontend/src/helpers/routeCalculations.js
- frontend/src/reducers/index.js
This PR simplifies the code for computing displaying route-level statistics and scores. It uses a Redux action to store computed statistics and scores for each route (for the current date/time selection). This allows UI components like RouteTable and RouteSummary to easily display route-level statistics and scores without needing to repeat the code to compute them. This will make it easier to add or remove statistics from the route table and route summary in the future.
The unused A/B/C/D letter grade calculations were removed to simplify the code, and the term 'grade' was replaced by 'score'.
Minor functionality changes include always sorting "--" rows to the bottom of the RouteTable in both ascending/descending sorts, and using medianWaitScore instead of waitRank in MapSpider to compute …
> Simplify code for computing and displaying route stats

- README.md
The readme was a bit confusing for new Portland developers since it sounded like it was only for SF.
Also, it had a lot of information about the technologies used in the frontend stack, but not much information about the backend stack.
> update readme to make it more applicable to non-SF developers, and add more information on the backend stack

- frontend/src/components/ReactSelect.jsx
Fix production bug where:
1.  User views the screen for a route and selects a direction, causing the react-selects to render.
2.  User returns to the dashbard via the left arrow button (upper left corner)
3.  User scrolls the dashboard.  This causes a javascript crash.  Apparently the scrolling triggers an event handler for the react-select which probably expects the react-select to be present and visible, but it is not.
n/a
n/a
> Quick fix for javascript crash after viewing react-select 

- frontend/src/components/ReactSelect.jsx
Replaces @exxonvaldez 's hotfix (#525 ).
I didn't understand at the time that the global object was quite so...global. As a result only the second react-select's listeners were being cleaned up.
Both screenshots are after returning to dashboard
<table>
<tr><td>Before</td><td>After</td></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/20414905/73464211-a776df00-43d2-11ea-81a3-aad5d031ecca.png" /></td>
<td><img src="https://user-images.githubusercontent.com/20414905/73464724-75b24800-43d3-11ea-92a0-a354e94a7ce6.png" /></td>
</tr>
> fix react-select event listener cleanup

- .github/workflows/test.yml
- README.md
- dev/docker-lint.bat
- dev/docker-lint.sh
- docker-compose.yml
- frontend/.eslintrc.json
- frontend/package.json
- frontend/src/actions/index.js
- frontend/src/components/ControlPanel.jsx
- frontend/src/components/DateTimePanel.jsx
- frontend/src/components/InfoByDay.jsx
- frontend/src/components/InfoScoreCard.jsx
- frontend/src/components/InfoTripSummary.jsx
- frontend/src/components/MapSpider.jsx
- frontend/src/components/MapStops.jsx
- frontend/src/components/RouteSummary.jsx
- frontend/src/components/RouteTable.jsx
- frontend/src/components/SidebarButton.jsx
- frontend/src/helpers/graphData.js
- frontend/src/helpers/mapGeometry.js
- frontend/src/helpers/routeCalculations.js
- frontend/src/screens/RouteScreen.jsx
Currently it seems that most frontend developers (including me) haven't been running `npm run lint` on their PRs. If one developer runs lint on their PR, lint will then make a lot of changes unrelated to their PR, which makes reviewing and merging difficult (e.g. https://github.com/trynmaps/metrics-mvp/pull/509).
However, in order for a developer to run `npm run lint`, they need npm installed on their host, but many developers do not have npm installed on their host, because normally npm runs inside a Docker container.
This PR adds scripts to allow developers using Docker to run lint inside a Docker container, so it is no longer necessary for developers to have npm installed on their host.
It also runs the lint task via Github Actions on each push so that we can see failing lint checks …
> add scripts for running lint within docker container; run lint via github actions

- frontend/src/components/MapSpider.jsx
- frontend/src/components/MapStops.jsx
- frontend/src/screens/RouteScreen.jsx
Fixes #530.
Fixes an issue where clicking stops on the map or the breadcrumbs would reset the date range because the query string was not set as a property on the action.
> preserve query string when clicking stops on map or breadcrumbs on route screen

- frontend/src/routesMap.js
A small fix to add query string support for our "Developer Tools" (data diagnostic) page.  This is something I missed when adding date params to the query string.  Noticed while testing #528 .
n/a
n/a
> Small fix to add query string support for the data diagnostic page

- docs/metrics_api.md
Change documentation to indicate a date is required for the interval metric type
> Fix graphql documentation for param input

- backend/compare_versions.py
- backend/compute_arrivals.py
- backend/compute_new.py
- backend/compute_stats.py
- backend/get_state.py
- backend/headways.py
- backend/metrics-api.py
- backend/models/arrival_history.py
- backend/models/eclipses.py
- backend/models/gtfs.py
- backend/models/metrics.py
- backend/models/precomputed_stats.py
- backend/models/schema.py
- backend/models/trynapi.py
- backend/models/wait_times.py
- backend/parse_timepoint_csv.py
- backend/route.py
- backend/routes.py
- backend/timetable.py
- backend/trips.py
- backend/vehicle.py
- backend/waits.py
I've been generating a picture of the logic of the backend code - I've got a handle on orion and tryn-api, and am busy working out how the backend talks to the tryn-api GraphQL endpoint, and in turn how the backend and frontend talk to each other (the end result of this should be a big, pretty SVG diagram that reduces the hurdle to backend dev work)
There are 1387 flake8 errors in the backend/ folder, of which 109 are related to imports - some of these errors are just stylistic, and could be overridden with a config file. However, having lots of redundant imports makes it hard to track which bits of the codebase are used where. This PR removes those redundant imports.
In general, if multiple people are going to be contributing backend code, I'd suggest auto-running yapf or autopep8 on …
> Clean unused imports

- backend/compute_stats.py
- backend/models/metrics.py
- backend/models/precomputed_stats.py
- backend/models/schema.py
- frontend/public/isochrone-worker.js
This change partially implements #554, adding a medianHeadway field on the DirectionIntervalMetrics GraphQL type to make it possible to show median service frequency for each route on the dashboard and route screen. This PR doesn't update the UI to actually show median service frequency yet.
To avoid increasing the size of the "combined" precomputed stats file, it doesn't store the median headways for each stop, but only the median of the median headways for all stops in each direction.
Similarly, the "combined" precomputed stats file now only stores the median of the median wait time and on-time rate for each stop. This reduces the file size from about 700 kB to about 650 kB. Most of the file size is due to the stats used for the travel time chart, average speed, and travel time …
> Precompute median service frequency (headway) for each direction, and add to GraphQL API

- backend/models/eclipses.py
- backend/models/metrics.py
- frontend/src/actions/index.js
- frontend/src/components/TravelTimeChart.jsx
Fixes several bugs with loop routes.
* SegmentIntervalMetrics were missing between last stop and first stop in GraphQL API
* TravelTimeChart didn't show time to return to first stop
* When computing arrival/departure times for the first or last stop of a loop route, it did not take into account the distance to one of the adjacent (last or first) stops. This caused problems with detecting arrivals at the 11th and Marshall stop on the Portland Streetcar B Loop, which is close to the 10th and Northrup stop.
* When determining arrival times for a loop route that crossed over itself (e.g. figure-eight or lollipop), every stop it passed close to was counted as an arrival, leading to a lot of extra arrivals. This caused issues with the TriMet loop routes 50, 53, and 84. The updated algorithm …
> fix bugs with loop routes

- docs/CODEOWNERS
- Removing Jose from backend who has been MIA for over 8 months
- Adding Will to backend who is skilled at Backend+Python+DS
- Adding Eddy to backend reviewers
> Update codeowners for backend reviewers

- frontend/src/components/RouteTable.jsx
Adding/removing a column in the route table required updating code in 3 different places: the column header definitions, the TableCell definitions for normal rows, and the help tooltip content. This made it difficult to modify the columns in the table. Also, there was some repetitive code for setting cell styles for each column. This PR refactors the RouteTable class so that each column is only defined in one place in the code. This should make it easier to make the columns configurable in the future (#553).
> refactor route table so columns are defined in one place

- backend/models/gtfs.py
Fixes #575 
- If there are routes that don't have sort_order when the first one does, it means that they are in the GTFS but not in Nextbus (at the time of this PR). This could be when a new route is added, and so it appears in the GTFS ahead of time so that it'll be on Google Maps (as that takes a few days to update GTFS) but not on Nextbus until the day it starts service. This PR puts the new routes at the end (sort order of 9999), unless they're a subway line (special case for TTC), in which case they go to the front (sort order of 0).
- Previously the sort_order from Nextbus was used if the first route had it, which was not the case for TTC. This PR uses the sort_order from Nextbus if any route has it, which is determined before sorting.
Expected Result / Testing:
Now when running …
> Exclude routes in GTFS but not Nextbus when sorting in save_routes

- frontend/public/manifest.json
- frontend/src/components/RouteTable.jsx
React wants stable "key" properties for items in a list, otherwise warnings are issued on the browser console.  The refactored RouteTable code was missing keys for the p tags that made up the "help" popover, as well as the TableCells that made up the table header.
Also fix manifest.json to use relative paths to the high res icons (for mobile bookmarks), because the production URL differs from dev ( / vs /frontend/build/).  This was added with the logo update.
.
.
.
n/a
> Fix missing keys in per column paragraphs and TableCells and use relative paths in manifest.json

- frontend/src/components/DateTimePopover.jsx
- frontend/src/routesMap.js
Fixes #550 
-DateTmePopover: Add an "Apply" button that does what "x" used to do, as in Uber Movement.  Make "x" into a cancel button that reverts the local form state.
- routesMap: Fix bug noted in #550 where second date range cannot be the default (yesterday) by adding a flag on the query string that signifies that the second range is active.
https://ot-terence-date-range-compare.herokuapp.com/
> DateTimePopover fixes from #461.

- backend/agencies/trimet.yaml
- backend/models/gtfs.py
Handles loop routes, routes with multiple branches, directions that only occur at certain times of day, hides some routes from the dashboard, and excludes certain stops at the beginning and end of routes to make end-to-end statistics more representative of typical performance.
> Add custom directions and route heuristics for TriMet

- frontend/src/actions/index.js
- frontend/src/components/DateTimePopover.jsx
- index.js: Fixed references to date/time parameter that should have been updated in the compare date range PR.  This fixes time of day options that were not being sent in the route metrics query.
- DateTimePopover: Fix react-hooks/exhaustive-deps compiler warning, which was
```
metrics-react-dev | ./src/components/DateTimePopover.jsx
metrics-react-dev |   Line 84:  React Hook useEffect has a missing dependency: 'resetLocalDateRangeParams'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```
which when fixed results in
```
metrics-react-dev | ./src/components/DateTimePopover.jsx
metrics-react-dev |   Line 74:  The 'resetLocalDateRangeParams' function makes the dependencies of useEffect Hook (at line 89) change on every render. To fix this, wrap the …
```
> Fix regression and warning from compare date range PR.

- frontend/src/screens/RouteScreen.jsx
Fixes #391 .
For SEO reasons, it helps to make the most important heading in your page an H1. For us, that would be the route name (e.g. "38-Geary") on a route page. 
This PR makes the route name render as an H1, but actually keep the same styling as all the other breadcrumbs.
Observe how the route name is an H1 but everything else is rendered as the default tag, H6; all the breadcrumb tags have the same styling regardless.
H6:
H1:
> Improve SEO by rendering route name as H1

- backend/models/gtfs.py
- backend/save_routes.py
Fixes #581. Fixes #584.
Muni's GTFS contains each route twice, once from before February 22, and again starting from February 22, when they modified service on a few routes. This PR modifies save_routes to remove routes that don't have any service_ids that cover the date in which the script is being run, which is set to the current date (when versioned GTFS is added the date will be made an argument).
Removes the duplicate routes, keeping the ones valid after February 22. Running Muni is still blocked by #576, which would need to be merged beforehand. 
- For TriMet, after removing the calendar.txt file and setting the date to a Sunday, all routes including the 92 South Beaverton Express (weekday peak-periods only) appear.
- For Muni, setting the date to February 22 (first date of changes) …
> Remove routes without any service_ids that cover today's date

- backend/models/trynapi.py
Resolves Issue #423, as to not longer store all vehicle
states for a chunk in memory, as this can cause out-of-memory
issues for agencies with a lot of vehicles (such as TTC).
This approach involves writing the chunks for each route for each date into a CSV file, which allows for appending vehicle rows. It avoids writing many small JSON files, which would take longer to load and assemble, and also uses less space.
Performance-wise the `get_state` function of compute_arrivals now takes about 10x longer for individual routes, excluding time spend on calls to `get_raw_state`. It shouldn't be an issue to deploy as it is, as 10x is, from about 0.5 to about 5 seconds for TTC route 32 (has 25-50 vehicles all day), and about 0.3 to about 2 seconds for tiny routes like TTC routes 30 (1 vehicle all …
> Store trynapi data by route on disk instead of in-memory

- frontend/src/components/NotFound.jsx
Fixes #216.
A more informative 404 page with a link to go back to safety. Adds a tiny bit of whimsy, too, like all the great 404 pages. It's no Fail Whale, but I did my best.
Before:
After:
Note that #607 automatically wraps the 404 page with a header bar, so I'm not adding that here.
Also, I had to manually add padding because our framework doesn't automatically add any. I would like to see that factored out into CSS at some point.
> Better 404 page

- backend/models/eclipses.py
- backend/models/trynapi.py
When fetching the state from tryn-api to compute arrivals, profiling showed that a significant amount of running time was spent in read_temp_chunk_state, which loaded a cache file in CSV format into memory, converted the data structure, and wrote a file in JSON format. However, the JSON format was only used by eclipses.produce_buses to initialize a DataFrame, which could also be done from the original CSV format without using JSON. 
This PR removes the JSON format and updates CachedState.get_for_route to return the DataFrame that used to be returned by eclipses.produce_buses. eclipses.find_arrivals is updated to take the DataFrame as a parameter instead of a dict.
> use CSV for storing per-route state instead of JSON for better performance

- backend/agencies/trimet.yaml
- backend/models/gtfs.py
- backend/save_routes.py
- docs/agencies.md
save_routes.py was raising an exception because trimet's GTFS file changed again and some of the custom directions no longer matched any shapes. Since this has been happening often, this PR updates save_routes.py to skip any invalid custom directions and raise an exception at the end, after saving the route configuration.
Also, if a custom direction matches multiple shapes, it will use the most common shape instead of raising an exception.
Updates the custom directions for trimet's latest GTFS file.
> skip invalid custom directions in save_routes.py instead of stopping

- frontend/src/components/InfoTripSummary.jsx
Very quick fix for no data error in InfoTripSummary. This is not an ideal fix just a patch so not getting blank screen on prod. Seems there was a change in commit: 
https://github.com/trynmaps/metrics-mvp/commit/cabe88a5ba1dc7f605b6cb267b1f6fff10cec69a
That defaulted scores to null instead of empty object. Just changed it back.
- A better fix would be handling for no data case and reflect that in the view; however, I don't know how common this is so might not be worth it. 
##Steps to test
Select route and set a trip with start and end stops. Trip summary cards should render greyed out.
> quick revert for no data bug

- backend/models/trynapi.py
On GKE, compute_new.py was failing when it tried to delete cache files from a directory that hadn't been created yet:
```
FileNotFoundError: [Errno 2] No such file or directory: '/app/backend/data/state_v2_trimet'
at remove_route_temp_cache (/app/backend/models/trynapi.py:165)
at get_state (/app/backend/models/trynapi.py:97)
at compute_arrivals_for_date_and_start_hour (/app/backend/compute_arrivals.py:22)
at compute_arrivals (/app/backend/compute_arrivals.py:61)
at <module> (compute_new.py:72)
```
This PR fixes this issue by creating the directory before calling remove_route_temp_cache.
> fix bug where get_state failed if cache dir did not already exist

- backend/agencies/muni.yaml
- backend/models/gtfs.py
The current GTFS feed from SF Muni starts on April 4, which caused get_active_routes to save an empty list of routes. This PR updates the behavior so if there are no active services, all routes in the GTFS feed will be saved.
It also removes a muni custom direction which no longer exists in the GTFS feed.
> if no routes currently have active services, save all routes

- docker-compose.yml
- frontend/package-lock.json
- frontend/package.json
- Match ESLint versions
- Use a TTY as it's required for React Development
Use `babel-eslint` 10.1.0 as it is required by `normalize.css` already, breaking the dependency tree if another version is used.
Use a TTY for local `docker-compose`. See https://github.com/facebook/create-react-app/issues/8688 for more information as to why this.
https://sfbrigade.slack.com/archives/C7HUYBHAA/p1586304906043500
> Fix local docker-compose

- backend/models/gtfs.py
Agencies normally update their GTFS a few days ahead so the one that gets downloaded ends up having no active routes. This could result in the wrong routes being shown on the dates just before the changes take effect, if for example a route is added or removed.
If there are no active routes on the provided date, save_routes will raise an exception and the routes will not be updated. The older version of routes will be used by the backend, which should result in the expected behaviour.
There could be the case where an agency schedules zero routes for the entire duration of their GTFS, but I don't see that happening.
> Skip updating GTFS if no active routes on date being run

- frontend/src/components/ControlPanel.jsx
- frontend/src/components/DateTimePanel.jsx
- frontend/src/components/DateTimePopover.jsx
- frontend/src/components/InfoIntervalsOfDay.jsx
- frontend/src/components/MapSpider.jsx
- frontend/src/components/MareyChart.jsx
- frontend/src/screens/Dashboard.jsx
- frontend/src/screens/DataDiagnostic.jsx
- frontend/src/screens/RouteScreen.jsx
The lint check has been failing since bumping the version of eslint in #615. This PR fixes the new lint errors.
> fix lint errors introduced by dependency bump

- frontend/.env.production
As the frontend is hosted on S3 the metrics API endpoint needs to be changed to point to the API running on google cloud, which can be reached through data.opentransit.city
> Change Metrics API production endpoint

- Dockerfile
A previous PR (#613) broke viewing the frontend when
deployed on nginx by changing the homepage from frontend/build
to https://muni.opentransit.city. This PR resolves this by
setting the PUBLIC_URL environment variable to frontend/build
when running npm run build from the Dockerfile, which is used
for all server deployments including Google Cloud, Heroku, and
by future users who want to deploy OpenTransit on their own
server using our Docker setup.
The static S3 serverless approach continues to work for
muni.opentransit.city but requires
modifying the URLs in frontend/package.json and in
frontend/public/CNAME for deploying a static site for other agencies
or environments which we don't officially support or document
as of yet.
> Allow frontend to load from nginx deployment
